version: 2

project_name: mysqlrouter_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: mysqlrouter_exporter
    main: .
    binary: mysqlrouter_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.buildDate={{ .Date }}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: git

