listen_address: ":9165"
metrics_path: "/metrics"
api_base_url: "https://127.0.0.1:8443/api/20190715"
api_user: "router_api_user"
api_password: ""
api_password_file: "/etc/mysqlrouter_exporter/router_api_password"
timeout_seconds: 5
insecure_skip_verify: true
tls_ca_file: ""
tls_cert_file: ""
tls_key_file: ""
collect_route_connections: false
router_config_file: "/var/lib/mysqlrouter/mysqlrouter.conf"
listener_check_enabled: true
listener_check_timeout_seconds: 1

